# Frontend
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fat-squirrels-fe
  description: ReNoMy Frontend
  tags:
    - react
  links:
    - url: https://github.com/maurosala/fat-squirrels
      title: "fat-squirrels"
      icon: "dashboard"
  annotations:
    github.com/project-slug: maurosala/fat-squirrels
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: "fat-squirrels"
    backstage.io/kubernetes-label-selector: "component=fat-squirrels"
    sonarqube.org/project-key: maurosala_fat-squirrels
    grafana/tag-selector: "fat-squirrels"
    prometheus.io/rule: "container_cpu_usage_seconds_total{namespace='fat-squirrels'}"
    prometheus.io/alert: 'Excessive Memory Usage'
spec:
  type: service
  lifecycle: experimental
  owner: "kerberus"
  consumesApis:
    - fat-squirrels-api
  dependsOn: ["component:fat-squirrels-be"]
  system: fat-squirrels-system
---
# Backend
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fat-squirrels-be
  description: ReNoMy Backend
  tags:
    - nodejs
    - api
  links:
    - url: https://github.com/maurosala/fat-squirrels
      title: "fat-squirrels"
      icon: "dashboard"
  annotations:
    github.com/project-slug: maurosala/fat-squirrels
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: "fat-squirrels"
    backstage.io/kubernetes-label-selector: "component=fat-squirrels"
    sonarqube.org/project-key: maurosala_fat-squirrels
    grafana/tag-selector: "fat-squirrels"
    prometheus.io/rule: "container_cpu_usage_seconds_total{namespace='fat-squirrels'}"
    prometheus.io/alert: 'Excessive Memory Usage'
spec:
  type: service
  lifecycle: experimental
  owner: "kerberus"
  providesApis:
    - fat-squirrels-api
  dependsOn: ["resource:fat-squirrels-db"]
  system: fat-squirrels-system
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fat-squirrels-api
  description: Todo API
  links:
    - url: https://krateo.io
      title: "krateo.io"
      icon: "dashboard"
  tags:
    - openapi
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: "kerberus"
  apiProvidedBy: fat-squirrels-be
  apiConsumedBy:
    - fat-squirrels-fe
  definition:
    $text: https://github.com/maurosala/fat-squirrels/blob/main/openapi.yaml
  system: fat-squirrels-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fat-squirrels-system
  description: AWS Cloud
  annotations:
    keptn.sh/project: krateo
spec:
  owner: "kerberus"
  domain: cloud-apps
  system: fat-squirrels-system
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fat-squirrels-db
  description: Stores todos
  links:
    - url: https://krateo.io
      title: "krateo.io"
      icon: "dashboard"
spec:
  type: database
  owner: "kerberus"
  system: fat-squirrels-system
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: cloud-apps
  description: fat-squirrels domain
spec:
  owner: "kerberus"
