{{- if .Values.app }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    component: "fat-squirrels"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
